services:
  ai-project:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai_project_container
    volumes: 
      - .:/app
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - TRANSFORMERS_OFFLINE=1
    
    command: python solution.py